import "./globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="grid grid-cols-12 grid-rows-12 bg-slate-200 h-screen w-full text-center">
        <header className="row-start-1 row-end-2 bg-yellow-300 w-full">
          <nav>navbar</nav>
        </header>
        <main className="row-start-2 row-end-11 bg-pink-50 w-fulls col-start-2 col-end-12">
          {children}
        </main>
        <footer className="row-start-11 row-end-13 bg-blue-400 w-full">
          <div>footer</div>
        </footer>
      </body>
    </html>
  );
}
